name: Julie Annlie
favicon: null
layout_spectrum: 0.5344768057111651
typography_spectrum: 0.41322793927975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e2e4'
    - '#353535'
    - '#5a5a5a'
    - '#b9b8b3'
    - '#818284'
  brandStrength: 0.5
  lightness: 0.8688638166058809
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
