name: Julie Annlie
favicon: null
layout_spectrum: 0.5344768057111651
typography_spectrum: 0.41322793927975
title: Julie AnnLie - fotograf og filmskaber
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#eff1f0'
    - '#9d928c'
    - '#016959'
    - '#02b83c'
  brandStrength: 0.125
  lightness: 0.8688638166058809
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
